// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkkofpuTued5OXTAQq954lUJCGnU8RCSI',
    appId: '1:249460808856:web:deb2c4261500382bc8c4ed',
    messagingSenderId: '249460808856',
    projectId: 'news-app-e6e51',
    authDomain: 'news-app-e6e51.firebaseapp.com',
    storageBucket: 'news-app-e6e51.appspot.com',
    measurementId: 'G-5WNJXJPMW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx4bhO9T-EGNRTsNdi-I9RO7xTKoSfT5s',
    appId: '1:249460808856:android:de97cd5af35a27cfc8c4ed',
    messagingSenderId: '249460808856',
    projectId: 'news-app-e6e51',
    storageBucket: 'news-app-e6e51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR4lw-LQGoJyRbvWrZHLZD354Ur78KmD4',
    appId: '1:249460808856:ios:de9a8275798d83e0c8c4ed',
    messagingSenderId: '249460808856',
    projectId: 'news-app-e6e51',
    storageBucket: 'news-app-e6e51.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR4lw-LQGoJyRbvWrZHLZD354Ur78KmD4',
    appId: '1:249460808856:ios:de9a8275798d83e0c8c4ed',
    messagingSenderId: '249460808856',
    projectId: 'news-app-e6e51',
    storageBucket: 'news-app-e6e51.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkkofpuTued5OXTAQq954lUJCGnU8RCSI',
    appId: '1:249460808856:web:1ced3a6fbb601515c8c4ed',
    messagingSenderId: '249460808856',
    projectId: 'news-app-e6e51',
    authDomain: 'news-app-e6e51.firebaseapp.com',
    storageBucket: 'news-app-e6e51.appspot.com',
    measurementId: 'G-ZCESCCCFV4',
  );
}
